### ISSUE TITLE
ToDo's: update tests and Github Actions

### ISSUE THREAD

**Issue by A-Buch** [A-Buch/IWR-Project-Effective-Software-Testing#1]
**ToDo's:**

- [x] update dependabot with automerge
- [x] merge/solve dependabot pull requests from February
- [x] automatically correct files with Ruff pre-commit hook used with CI [https://thomasthornton.cloud/2022/08/04/running-pre-commit-hooks-as-github-actions/](link_precommit4CI), [https://interrupt.memfault.com/blog/pre-commit#continuous-integration-ci](link_precommit4CI_2)
- [x] fixture test_data
- [ ] update README: poetry env, automatic testing (fixtures and mocking, pre-commit hooks, CI, pytest and unitest)

maybe:
- [ ] test example with monkeypatching
- [ ] example with pytest-datadir

**Comment by A-Buch** [comment]
**Black and Ruff autofix line-length** 
Wait until Black (or Ruff formatter) can handle various types of too long lines [E501]. 
`black --preview` (version 24.4.2) currently fixes a few versions of too long lines and fails for others.
- [ ]  update pre-commit as soon as stable version for autofix of line-length is available
